### ISSUE TITLE
好像不能用了

### ISSUE THREAD

**Issue by cenla** [lmk123/alipay-bills#1]
/clear"}}」，正在重试……
[2017-10-24 08:50:33] 正在跳转到登陆页……
[2017-10-24 08:50:33] 正在输入用户名……
[2017-10-24 08:50:33] 尝试登陆时失败：「{"errorMessage":"Element is not currently interactable and m
ay not be manipulated","request":{"headers":{"Accept":"application/json; charset=utf-8","Connection"
:"close","Content-Length":"2","Content-Type":"application/json;charset=UTF-8","Host":"192.168.3.151:
52819"},"httpVersion":"1.1","method":"POST","post":"{}","url":"/clear","urlParsed":{"anchor":"","que
ry":"","file":"clear","directory":"/","path":"/clear","relative":"/clear","port":"","host":"","passw
ord":"","user":"","userInfo":"","authority":"","protocol":"","source":"/clear","queryKey":{},"chunks
":["clear"]},"urlOriginal":"/session/5374e470-b855-11e7-aef1-37721cb12716/element/:wdc:1508806233650
/clear"}}」，正在重试……
[2017-10-24 08:50:33] 正在跳转到登陆页……
[2017-10-24 08:50:34] 正在输入用户名……
[2017-10-24 08:50:34] 尝试登陆时失败：「{"errorMessage":"Element is not currently interactable and m
ay not be manipulated","request":{"headers":{"Accept":"application/json; charset=utf-8","Connection"
:"close","Content-Length":"2","Content-Type":"application/json;charset=UTF-8","Host":"192.168.3.151:
52819"},"httpVersion":"1.1","method":"POST","post":"{}","url":"/clear","urlParsed":{"anchor":"","que
ry":"","file":"clear","directory":"/","path":"/clear","relative":"/clear","port":"","host":"","passw
ord":"","user":"","userInfo":"","authority":"","protocol":"","source":"/clear","queryKey":{},"chunks
":["clear"]},"urlOriginal":"/session/5374e470-b855-11e7-aef1-37721cb12716/element/:wdc:1508806234172
/clear"}}」，正在重试……
[2017-10-24 08:50:34] 正在跳转到登陆页……
[2017-10-24 08:50:34] 正在输入用户名……

**Comment by lmk123** [comment]
是的，这个项目不再维护了，支付宝变动的太频繁了。
